// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// RegistrationToken A token for the operator to give to the AGW. It keys to logical and network ID.
// swagger:model registration_token
type RegistrationToken string

// Validate validates this registration token
func (m RegistrationToken) Validate(formats strfmt.Registry) error {
	return nil
}
